version: '3'
services:
  api:
    build:
      context: .
    command: npm run start:api
    volumes:
      - .:/usr/src/app
    environment:
      - VIRTUAL_HOST=api.sports-app.docker
      - NODE_ENV=development
    depends_on:
      - db
      - proxy

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sportsapp

  proxy:
    container_name: proxy
    image: codekitchen/dinghy-http-proxy
    environment:
      - DNS_IP=127.0.0.1
      - CONTAINER_NAME=proxy
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sportsapp?sslmode=disable
    depends_on:
      - db

